### ISSUE TITLE
The original author of tp_FogOfWar.lua was "fuckers"

### ISSUE THREAD

**Issue by knorker** [SpringCabal/Corruption#1]
https://github.com/SpringCabal/Corruption/blob/master/LuaUI/Widgets/tp_FogOfWar.lua is an early version of the fog-of-war widget, with as far I can see only slight changes:
-vertices coloring is different
-Some constants changed like res=75 to res=32
https://github.com/SpringCabal/Corruption/commit/acfd63d575fef50b14d734711c42bd7116f63d28 , etc

The changes are imo small  tweaks so it is not fair to remove original author  "fuckers" from author field and replace with own name.

**Comment by gajop** [comment]
Honestly original authors/licence was just nonsense.
Maybe the "horses. horses everywhere." licence doesn't ask for attribution? Who knows.
Anyway, should've put my name after the original authors though.
The changes weren't minor though (in effect), and were based on this:
https://springrts.com/phpbb/viewtopic.php?f=1&t=28342&p=524291&hilit=jazcash#p524340
https://springrts.com/phpbb/viewtopic.php?f=1&t=28342&hilit=jazcash&start=20#p524363

**Comment by knorker** [comment]
> Maybe the "horses. horses everywhere." licence doesn't ask for attribution? Who knows.

the rider should know.
